добавил задание space age
AntonKlabukov90/javascript pull request #2
Opened 2024-01-18 15:31 UTC by AntonKlabukov90

2024-01-18 16:51 UTC, burtovoy requested changes

2024-01-18 16:51 UTC, burtovoy commented on space-age/space-age.js
> +  const map = new Map(Object.entries(planetsTime));
Есть варианты менее хитро написать? Почему Map именно

2024-01-18 16:51 UTC, burtovoy commented on space-age/space-age.js
> +  return ((actualAge / (earthYear * (map.get(planet)))).toFixed(2)*1)
Для чего *1 в конце? Там тип преобразуется? Неявного преобразования нужно избегать

2024-01-19 11:11 UTC, AntonKlabukov90 commented on space-age/space-age.js
> +  const map = new Map(Object.entries(planetsTime));
Да, можно сделать менее хитро например через конструкцию switch или if else, что потребует написания большего объема кода. Можно реализовать через итерацию object циклом for in. Я выбрал Map потому что более новая конструкция появилась только в ES6, быстрая реализация метода get и наличии большего количества методов, которые не нужно писать вручную. Оставить так или переписать менее хитро?

2024-01-19 11:12 UTC, AntonKlabukov90 commented on space-age/space-age.js
> +  return ((actualAge / (earthYear * (map.get(planet)))).toFixed(2)*1)
Да, согласен. Строгой типизации нет , постоянно забываю об этом. Уже исправил

2024-01-19 12:00 UTC, burtovoy commented on space-age/space-age.js
> +  const map = new Map(Object.entries(planetsTime));
Менее хитро )

2024-01-21 12:45 UTC, merged